<?php

function blinc_form_block_admin_configure_alter($form, &$form_state, $form_id) {
  $block = array(
    'module' => $form_state['build_info']['args'][0],
    'delta' => $form_state['build_info']['args'][1],
  );

  $contexts = blinc_get_block_contexts($block);
}

function blinc_get_block_contexts($block) {
  $query = db_select('blinc', 'b');
  $query->join('context', 'c', 'b.context = c.name');

  $result = $query->fields('c', array('name'))
    ->condition('b.module', $block['module'])
    ->condition('b.delta', $block['delta'])
    ->execute();

  $contexts = $result->fetchAllKeyed();

  return $contexts;
}

function blinc_context_registry_alter($registry) {
  $contexts = context_load();
  if (!empty($contexts)) {
    blinc_update_contexts($contexts);
  }
}

function blinc_update_contexts($contexts) {
  foreach ($contexts as $context) {
    if (_blinc_context_has_block_reaction($context) {
      foreach ($context->reactions['block']['blocks'] as $block) {
        //$query = db_update('blinc'
      }
    }
  }
}

function _blinc_context_has_block_reaction($context, $block) {
  return isset($context->reactions['block']);
}
